using System;
using System.IO.Compression;
using System.Linq;
using System.Web.Mvc;

namespace CompressR.MVC
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class DeflateAttribute : BaseCompressAttribute
    {
        public DeflateAttribute(bool requireCompression = false)
            : base(requireCompression)
        {
        }

        /// <summary>
        /// Override to compress the content that is generated by
        /// an action method.
        /// </summary>
        /// <param name="filterContext"></param>

        public override void OnResultExecuted(ResultExecutedContext filterContext)
        {
            CompressFactory.Compress(filterContext, RequireCompression, Constants.Deflate, CompressionLevel);
        }
    }
}