using System;
using System.IO.Compression;
using System.Linq;

namespace CompressR.MVC
{
    public sealed class GzipAttribute : BaseCompressAttribute
    {
        public GzipAttribute(bool requireCompression = false)
            : base(requireCompression)
        {
        }

        /// <summary>
        /// Override to compress the content that is generated by
        /// an action method.
        /// </summary>
        /// <param name="filterContext"></param>
        public override void OnActionExecuting(System.Web.Mvc.ActionExecutingContext filterContext)
        {
            CompressFactory.Compress(filterContext, RequireCompression, Constants.Gzip, CompressionLevel);
        }
    }
}